### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by cs-xiao** [yuta-hi/pytorch_similarity#2]
Hi，when all the elements of input are 0，the gc is 0.
eg. 
x = torch.zeros((1, 1, 128, 128))
gc, gc_m = model(x, torch.zeros_like(x))
print(gc.item())  ->  0

**Comment by yuta-hi** [comment]
Thank you for your kind comment.
What you're saying is that if the two inputs are zero vectors, then the GC should be 1, right?

This can be fixed by changing line 73 of functional.py to the following.
Before:
`ncc = torch.div(dev_xy, torch.sqrt( torch.mul(dev_xx_sum, dev_yy_sum)) + eps)`
After:
`ncc = torch.div(dev_xy + eps, torch.sqrt( torch.mul(dev_xx_sum, dev_yy_sum)) + eps)`

**Comment by cs-xiao** [comment]
Yes，good job，man！

**Comment by yuta-hi** [comment]
Thanks a lot.
